[workspace]
[package]
name = "third-party"
version = "0.0.0"
publish = false

[lib]
path = "/dev/null"

[dependencies]
autocxx-bindgen = "=0.62.1"
aquamarine = "0.1"
cc = "1.0"
clap = { version = "3.1.2", features = ["cargo"] }
cxx-gen = "0.7.78"
cxx = "1.0.78"
env_logger = "0.9.0"
indexmap = { version = "1.8", features = ["serde"] }
indoc = "1.0"
itertools = "0.10.3"
log = "0.4"
miette = "5"
once_cell = "1.7"
pathdiff = "0.2.1"
prettyplease = { version = "0.1.15", features = ["verbatim"] }
proc-macro-error = "1.0"
proc-macro2 = "1.0.11"
quote = "1.0"
regex = "1.5"
rustversion = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
strum_macros = "0.24"
#syn = "1.0.39"
moveit = { version = "0.5", features = [ "cxx" ] }
tempfile = "3.1"
thiserror = "1"
version_check = "0.9"

[dependencies.syn]
version = "1.0.39"
features = ["full", "extra-traits"]
